root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  entrypoint = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "dist"]
  delay = 200
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"
  poll = true
  poll_interval = 500

[log]
  time = true

[misc]
  clean_on_exit = true
